#cloud-config
disable_root: False
ssh_enabled: True
ssh_pwauth: True

#create user
users:
  - name: nutanix
    groups: sudo
    shell: /bin/bash
    lock_passwd: false
    sudo: ['ALL=(ALL) NOPASSWD:ALL']
    passwd: $6$4guEcDvX$HBHMFKXp4x/Eutj0OW5JGC6f1toudbYs.q.WkvXGbUxUTzNcHawKRRwrPehIxSXHVc70jFOp3yb8yZgjGUuET.
  - name: centos
    ssh-authorized-keys:
      - ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAACAQDFLmMnowDKA2s2R/GZveK34Xr3kcWaU7WyoxbjFNzjJJKuN8NwrhBzwxJEKEb+jPLsQO5WWjjMkbj8wF14HcCLD3Syfrh1myeF8HETXp1djeAspo2ltPKfQnUm4XbD5Yvbq+TUVWJMg6WncnmqibbBsPbk9STnr+fKIp/OZw5U18ZkTV2Yu0m43fdYt16/FlEpXKtF+lpNy8AnXTpmyiyXabQcaYOjtA5ezKGkL+hvEgsbTjWGW3+zXltbk4dEyN1HrYu3RSKhKIm3Ep6vsrC7PCixFMojfKdg+d42QQFcRRhGKy9iZkbqCT2SY2Gcf6pc3DegSLzP+Ea+He5oj1Bjp+liHGpScxZL8CTFtSpkhtVD07sRxav2mYiAS+zSogeftS9G1i48JI85gOr0BYFPfvILQUz5zE5snhwPyClAFvdwDvRldzbJVuJef2VGWeAmH0YBawGo+Vd0U01JIEVbbcnasFkxsPUh6Pq3JlxzlRzMnIbeb/m81ChJSlhrUs5Ex2CGaF5OoJZo8UQ2T5ca/aDK2WWFjEzIpChRP7V9br5I06BJj6zme/5ddpCRJxavRi+X0shQ101A7KMhFsU9LJSPY86tIy8EnTs4LYXvT6uk/GrZwC9hFYExUoZMbqHbLBAYTFcSBKFEM4ezLn9NqvyHtqMDTjoy++oO49k2TQ== shankar@C02ZX0DDLVDM
#set password
#chpasswd:
#    list: |
#        SETYOURNAME:nutanix/4u
#    expire: False

timezone: Asia/Singapore


yum_repos:
  epel-release:
    baseurl: http://download.fedoraproject.org/pub/epel/7/$basearch
    enabled: true
    failovermethod: priority
    gpgcheck: true
    gpgkey: http://download.fedoraproject.org/pub/epel/RPM-GPG-KEY-EPEL-7
    name: Extra Packages for Enterprise Linux 7 - Release

package_update: true
package_upgrade: true

packages:
  - gcc-c++
  - make
  - unzip
  - bash-completion
  - python-pip
  - ntp
  - ntpdate
  - python36
  - python36-setuptools
  - htop
  - wget
  - iotop
  - xfs*
  - bc
  - unzip
  - lvm2*
  - java-1.8.0-openjdk
  - stress-ng
  - nginx
  - telnet

runcmd:
  - systemctl stop firewalld
  - systemctl disable firewalld
  - /sbin/setenforce 0
  - sed -i -e 's/enforcing/disabled/g' /etc/selinux/config
  - /bin/python3.6 -m ensurepip
  - pip install -U pip
  - ntpdate -u -s 0.pool.ntp.org 1.pool.ntp.org 2.pool.ntp.org 3.pool.ntp.org
  - systemctl restart ntpd
  - systemctl enable nginx
  - wget http://10.38.46.50/bundle.tar.gz -O /home/nutanix/bundle.tar.gz
  - tar -zxvf /home/nutanix/bundle.tar.gz
  - unzip /home/nutanix/node_bundle/vdbench50407.zip
  - /bin/bash /home/nutanix/node_bundle/ne.bash
  - echo "deployment completed" > /home/nutanix/done.txt
  - reboot


final_message: CentOS 7 Machine setup successfully!